#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR/out/build/x64-Debug/HotdogCraftGame

gdb --silent -batch -ex 'run' -ex 'backtrace' --args ./HotdogCraftGame